434 step goal command
PerfectFit-project/virtual-coach-rasa pull request #186
Opened 2023-09-14 12:35 UTC by bscheltinga

Fixes: https://github.com/PerfectFit-project/virtual-coach-issues/issues/434

@wbaccinelli note, I did not test this yet.

2023-09-18 10:07 UTC, wbaccinelli requested changes
Good to have the new functionality! I tested it but the intent is not recognized and I got some errors due to the empty steps and the unset slot. I left few comments. can you address them?

2023-09-18 10:07 UTC, wbaccinelli commented on Rasa_Bot/domain/domain_idle_commands.yml
> +    - text: "Het stappendoel voor vandaag is {pa_goal} stappen. 🎯"
I cannot find where this slot is defined and set. Are you sure that it is managed somewhere?

2023-09-20 07:52 UTC, bscheltinga commented on Rasa_Bot/actions/actions_idle_commands.py
> +        today_steps = steps_data[0]['steps']
Yes, that could occur. Nice catch

2023-09-20 07:59 UTC, bscheltinga commented on Rasa_Bot/domain/domain_idle_commands.yml
> +    - text: "Het stappendoel voor vandaag is {pa_goal} stappen. 🎯"
Good catch, I looked at another action (action_notifications_get_daily_step_goal) and took not the slot name, but variable name. Fixed it!

2023-09-20 08:56 UTC, bscheltinga commented on Rasa_Bot/actions/actions_idle_commands.py
> +        today_steps = steps_data[0]['steps']
Fixed this in other functions as well

2023-09-20 08:59 UTC, bscheltinga commented
> Good to have the new functionality! I tested it but the intent is not recognized and I got some errors due to the empty steps and the unset slot. I left few comments. can you address them?

I tried the intent last time, but it indeed was not working. I added an intent typo-option, retrained and now the intent is recognized :)

2023-09-20 09:17 UTC, bscheltinga commented
> > Good to have the new functionality! I tested it but the intent is not recognized and I got some errors due to the empty steps and the unset slot. I left few comments. can you address them?
> 
> I tried the intent last time, but it indeed was not working. I added an intent typo-option, retrained and now the intent is recognized :)

But now the 'uitleg' intent is not recognized...

2023-09-21 11:23 UTC, wbaccinelli approved these changes
Great, it works for me now!

2023-09-21 11:38 UTC, merged

2023-09-21 11:42 UTC, bscheltinga commented
I did the merge, feels a bit like my 'last dance'...